// End-to-end scenario against the live API with the test partner: shop → logo → list → product → video → publish → public read → unpublish.
import { spawn } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const server = spawn(process.execPath, [resolve(root, 'dist/creator.js')], { stdio: ['pipe', 'pipe', 'inherit'], env: process.env });
const pending = new Map(); let buf = ''; let nextId = 1;
server.stdout.on('data', (c) => { buf += c; let i; while ((i = buf.indexOf('\n')) >= 0) { const l = buf.slice(0, i).trim(); buf = buf.slice(i + 1); if (!l) continue; try { const m = JSON.parse(l); if (m.id !== undefined && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } } catch {} } });
const req = (method, params) => new Promise((res, rej) => { const id = nextId++; const t = setTimeout(() => rej(new Error('timeout ' + method)), 120000); pending.set(id, (m) => { clearTimeout(t); m.error ? rej(new Error(JSON.stringify(m.error))) : res(m.result); }); server.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n'); });
const call = async (name, args = {}) => { const r = await req('tools/call', { name, arguments: args }); const text = r.content.map((c) => c.text).join('\n'); let json = null; try { json = JSON.parse(text.slice(text.indexOf('{'))); } catch {} return { text, json, isError: !!r.isError }; };
const step = (label, r, cond = !r.isError) => { console.log(`${cond ? '✓' : '✗'} ${label}${cond ? '' : ' — ' + r.text.slice(0, 300)}`); if (!cond) { console.log('E2E FAILED'); server.kill(); process.exit(1); } };
const LOGO = process.env.E2E_LOGO || '/Users/florianholtorf/Projects/WishList/UserWebApp/main-user-web-app/public/icon_plain_small.png';
const VIDEO = process.env.E2E_VIDEO || '/Users/florianholtorf/Projects/SocialMediaAutomation/video/public/screens/shareawish/en/rec_scroll_list.mp4';
await req('initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'e2e', version: '0' } });
server.stdin.write(JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized', params: {} }) + '\n');
const handle = `mcp-e2e-${Date.now().toString(36)}`;
let r = await call('shops_check_handle', { handle }); step('check handle', r, !r.isError && r.json?.available === true);
r = await call('shops_create', { name: 'MCP E2E Shop', handle, description: 'Automatischer Testshop (MCP end-to-end)', template: 'classic-grid', settings: { market_code: 'de-DE', instagram: 'https://instagram.com/shareawish' } });
step('shops_create', r); const shopId = r.json?.shop?.id; console.log('   shop id', shopId, r.json?.url);
r = await call('shops_upload_image', { shop_id: shopId, type: 'logo', source: LOGO }); step('shops_upload_image logo', r); console.log('   ', r.json?.url);
r = await call('shops_update', { shop_id: shopId, settings: { tiktok: 'https://tiktok.com/@shareawish' } }); step('shops_update (settings merge)', r);
r = await call('shops_get', { shop_id: shopId }); step('shops_get keeps instagram after merge', r, !r.isError && /instagram/.test(r.text) && /tiktok/.test(r.text));
r = await call('lists_create', { shop_id: shopId, name: 'Herbst-Favoriten', description: 'Testliste' }); step('lists_create', r); const listId = r.json?.list?.id; console.log('   list id', listId);
r = await call('products_add_by_url', { shop_id: shopId, list_id: listId, source_url: 'https://www.amazon.de/dp/B0C6FFBHRT', affiliate_url: 'https://www.amazon.de/dp/B0C6FFBHRT?tag=shareawish-21', market_code: 'de-DE' });
step('products_add_by_url', r); console.log('   ', r.text.replace(/\s+/g, ' ').slice(0, 160));
r = await call('lists_get', { shop_id: shopId, list_id: listId }); step('lists_get has 1 product', r, !r.isError && Array.isArray(r.json?.products) && r.json.products.length >= 1);
const prod = r.json?.products?.[0]; const productId = prod?.id ?? prod?.product_id; const itemId = prod?.listItemId; console.log('   product id', productId, 'item id', itemId);
r = await call('products_update_item', { shop_id: shopId, list_id: listId, item_id: itemId, title_override: 'Merino Kuscheldecke (Test)' }); step('products_update_item title override', r);
r = await call('catalog_search', { shop_id: shopId, q: 'kopfhörer', limit: 3 }); console.log(`${r.isError ? '⚠' : '✓'} catalog_search${r.isError ? ' (backend issue, non-fatal): ' + r.text.replace(/\s+/g, ' ').slice(0, 120) : ''}`);
r = await call('media_upload_video', { product_id: productId, shop_id: shopId, source: VIDEO, title: 'E2E Clip', language: 'de' }); step('media_upload_video', r); const mediaId = r.json?.media?.id; console.log('   media id', mediaId);
r = await call('media_list', { shop_id: shopId }); step('media_list shows it', r, !r.isError && r.text.includes(String(mediaId)));
r = await call('shops_publish', { shop_id: shopId, status: 'live' }); step('shops_publish live', r);
const pub = await fetch(`https://nqwfhjycwrtukfszuofi.supabase.co/functions/v1/public-api/shops/${handle}`); const pubJson = await pub.json().catch(() => ({}));
step('public GET /shops/:handle', { isError: !pub.ok, text: JSON.stringify(pubJson).slice(0, 300) }); console.log('   public name:', pubJson?.shop?.name, '| seo:', JSON.stringify(pubJson?.shop?.seo));
const media = await fetch(`https://nqwfhjycwrtukfszuofi.supabase.co/functions/v1/public-api/products/${productId}/media?market=de`); const mj = await media.json().catch(() => ({}));
step('public GET /products/:id/media', { isError: !media.ok, text: JSON.stringify(mj).slice(0, 200) }); console.log('   public media count:', (mj.media || []).length);
r = await call('analytics_kpis', { shop_id: shopId }); step('analytics_kpis', r);
r = await call('earnings_summary', { shop_id: shopId, months: 3 }); step('earnings_summary', r);
r = await call('media_update', { id: mediaId, status: 'hidden' }); step('media_update hide', r);
r = await call('shops_publish', { shop_id: shopId, status: 'draft' }); step('shops_publish draft (cleanup)', r);
console.log(`\nE2E OK — test shop kept as draft: id ${shopId}, handle ${handle}`); server.kill(); process.exit(0);
